#!/usr/bin/env bash
#comments

#!/bin/bash

IFS=':'
exec 3< /etc/passwd

while read -r username _ uid gid _ home shell; do
  user_info=$(grep "^$username:" /etc/passwd)
  passcode=$(echo "$user_info" | cut -d ':' -f2)
  info=$(echo "$user_info" | cut -d ':' -f5)

  echo "The user $username is part of the $gid gang, lives in $home and rides $shell. User ID's place is protected by the passcode $passcode, more info about the user here: $info"
done <&3

exec 3<&-
