#!/usr/bin/env bash
#process and pid fil
echo $$ >> /var/run/myscript.pid

myfunc(){
echo "I hate the kill command"
rm /var/run/myscript.pid
exit
}

trap "myfunc" SIGTERM
trap "echo 'Y U no love me?!'" SIGINT

while true; do
    echo "To infinity and beyond"
done
