#!/usr/bin/env bash
#process and pid file
echo "$$" > /var/run/myscript.pid
trap "echo'I hate the kill command'" SIGTERM
trap "echo'Y U no love me?!'" SIGINT
trap "rm /var/run/myscript.pid" SIGTERM || SIGQUIT
while true;
do 
echo "To infinity and beyond"
done
