#!/usr/bin/env bash
#handling background processs
#!/bin/bash

if [ "$1" == "start" ]; then
    if [ -f "/var/run/my_process.pid" ]; then
        echo "Error: Process is already running."
        exit 1
    fi

    ./manage_my_process &
    echo $! > /var/run/my_process.pid
    echo "manage_my_process started"
elif [ "$1" == "stop" ]; then
    if [ ! -f "/var/run/my_process.pid" ]; then
        echo "Error: Process is not running."
        exit 1
    fi

    PID=$(cat /var/run/my_process.pid)
    kill $PID
    rm /var/run/my_process.pid
    echo "manage_my_process stopped"
elif [ "$1" == "restart" ]; then
    if [ ! -f "/var/run/my_process.pid" ]; then
        echo "Error: Process is not running."
        exit 1
    fi

    PID=$(cat /var/run/my_process.pid)
    kill $PID
    rm /var/run/my_process.pid

    ./manage_my_process &
    echo $! > /var/run/my_process.pid
    echo "manage_my_process restarted"
else
    echo "Usage: $0 {start|stop|restart}"
    exit 1
fi
