#!/usr/bin/env bash
#manging background processes
start_action() {
	./manage_my_process &
	echo $! > /var/run/my_process.pid
}

stop_action() {
	kill manage_my_process
	pkill -f ./manage_my_process
	sudo rm /var/run/my_process.pid
}

case "$1" in
start)
	start_action
	echo "manage_my_process started"
	;;

stop)
	stop_action
	echo "manage_my_process stopped"
	;;

restart)
	stop_action
	start_action
	echo "manage_my_process restarted"
	;;

*)
	echo "Usage: manage_my_process {start|stop|restart}"
	;;
esac
